### ISSUE TITLE
Controller inputs (PS5 Dualsense) incorrect

### ISSUE THREAD

**Issue by NaccacheC** [timkurvers/valheim-macos#11]
When using a dualsense controller, the game recognises the controller but the inputs are all jumbled. Input is fine within Steam Big Picture. When the game is launched, Steam recognises the dualsense controller, and an Xbox 360 controller that shows no inputs.

**Comment by timkurvers** [comment]
Hm, bit out of my depth here. I am assuming that controller works just fine for other Steam games?

**Comment by NaccacheC** [comment]
Yeah sorry, should have mentioned that. The controller works fine both with and without steam controller support in other games. Hoping someone else might be able to chip in, thanks!

**Comment by Ghostkwebb** [comment]
Well the game doesn't even detect my ds4 for some reason

**Comment by Tarik1700** [comment]
Same issue here, dualsense is fine in macos and steam, but in game the up and down of right joystick is not mapped or recognized at all

**Comment by sandlotie** [comment]
Same thing, but if you use Steam Input and replace everything with keyboard buttons, and use the joystick as a mouse, it works without any problems, as if the game itself does not understand gamepad input. (DualSense)

**Comment by ellkrauze** [comment]
@sandlotie Hello! Would you kindly share the details how exactly did you "replaced everything with keyboard buttons, and used the joystick as a mouse" in the Steam Input?

**Comment by sandlotie** [comment]
> @sandlotie Hello! Would you kindly share the details how exactly did you "replaced everything with keyboard buttons, and used the joystick as a mouse" in the Steam Input?

@ellkrauze I moved `Valheim.app` to applications folder, open Steam for mac and just go to `Steam Library -> Valheim -> Properties -> Controller -> Steam Input` and after this you see Controller button on Valheim page in library. You click on this button and a menu opens to select the controller layout and you can either create your own or find a suitable layout in the community layouts that uses the keyboard buttons instead of the controller buttons.
Although Steam overlay doesn't work in the game itself, but after starting the game it shows that I'm playing Valheim and the layout selected in Steam Input is applied. 

Personally, the layout of Valheim Controls from mugg455 suited me best after some minor changes.
Although the interaction with menus, like chests and inventory can be frustrating. But overall it's playable.
If I'm not clear about something, then tell me
<img width="640" alt="image" src="https://github.com/timkurvers/valheim-macos/assets/51976642/414deff6-11bd-4bfa-8c54-ed6ccd38a115">

**Comment by tbergeron** [comment]
Same thing here with a DS4 nothing works. Wish I could use it.

**Comment by ellkrauze** [comment]
The Xbox controller works well when connected via Bluetooth. If you connect it correctly, you can move the cursor with the right stick. However, the game itself is not controller friendly.

**Comment by SIX10** [comment]
> The Xbox controller works well when connected via Bluetooth. If you connect it correctly, you can move the cursor with the right stick. However, the game itself is not controller friendly.

What is your method for connecting the Xbox controller to Bluetooth? I've found multiple ways for MacOS and they've all been janky for me so far.

**Comment by ellkrauze** [comment]
@SIX10 I usually connect my Xbox controller the following way:
1. Press and hold the controller's Connect button for a few seconds to put the controller into pairing mode. This makes it discoverable by your Apple device.
2. Open Bluetooth settings on your macbook, then select the controller from the list of nearby devices.
3. Now the cursor can be moved using the right stick.
<img width="291" alt="image" src="https://github.com/timkurvers/valheim-macos/assets/51443765/e5eb6499-8401-4492-bc72-e8c4994a06fb">

**Comment by ezamelczyk** [comment]
My dualsense is not picked up at all by valheim. Works fine in other games native and under wine.

**Comment by ezamelczyk** [comment]
I do have to admit that I'm very impressed by this project. With fixed controller handling IG could confidently put it up on steam as a port and I don't think people would've complained at all. It's running very well on my m1 pro. I imagine with proper metal support and arm build it will be buttery smooth.

**Comment by jacktho** [comment]
+1 for the Switch Pro Controller

**Comment by timkurvers** [comment]
Closing this issue as the official macOS client is now available! 🥳 (see #104)
