### ISSUE TITLE
Public test build, please?

### ISSUE THREAD

**Issue by hvab** [timkurvers/valheim-macos#29]
Any chance to get public test build by this script? For example latest [Hildir's patch](https://store.steampowered.com/news/app/892970/view/6662560248440866810).

**Comment by timkurvers** [comment]
Hi there! That should be technically possible. I may have a look at it this weekend if time permits.

**Comment by hvab** [comment]
It would be great! Thank you! I tried to transfer new data from the [Steam depot](https://steamdb.info/app/892970/depots/) to the script myself, but I got stuck with the fact that the test branch has a password (`yesimadebackups`) and did not find the manifest for the test build.

**Comment by osirion** [comment]
Tried doing this myself by modifying the version and buildid. It downloaded the files, but then failed at the step after with a "cp" failure. No such file or directory since it appears to have downloaded the files into the 11422039 (normal) directory instead of the 11535571 (public-test) directory.

**Comment by osirion** [comment]
This is how I resolved it:
edit build.sh:

```
buildid=11535571
manifestid=9217850553460069452
version="0.217.6"
beta="public-test"
betapassword="yesimadebackups"
```

Then edit the line that looks like so:
`dotnet depotdownloader-2.4.7/DepotDownloader.dll -app $appid -depot $depotid -manifest $manifestid -os linux -username "$username"`
To be like so:
`dotnet depotdownloader-2.4.7/DepotDownloader.dll -app $appid -depot $depotid -manifest $manifestid -os linux -username "$username" -beta "$beta" -betapassword "$betapassword"`

**Comment by osirion** [comment]
Ok, correction, the above would of worked - I'm sure, if one had the correct manifestid - which I cannot seem to find for the life of me...

**Comment by timkurvers** [comment]
Thanks for looking into this @osirion!

If I remember correctly the only reason we specified the manifest ID was due to a [Steam platform bug](https://github.com/SteamRE/DepotDownloader/issues/428). This has been worked around in DepotDownloader 2.5.0. So in theory using that particular version (or newer) and dropping `-manifest` altogether should work. I managed to get a hold of the beta files that way.

Have the following idea in my head: putting this beta-variant of the script in a `beta`-branch here on GitHub, which would allow us to keep the main script clean. Just haven't had the time to test it out yet. 😊

**Comment by osirion** [comment]
Ahh! Great, can confirm that updating the build script to use Depot Downloader 2.5 did the trick. Was able to run the public-test version with no issues then :) Thanks @timkurvers !

**Comment by hvab** [comment]
> Ahh! Great, can confirm that updating the build script to use Depot Downloader 2.5 did the trick. Was able to run the public-test version with no issues then :) Thanks @timkurvers !

Hello! Can you please share the build.sh code? The above example doesn't work for me even if I set Depot Downloader 2.5.

**Comment by osirion** [comment]
@hvab - something like this...

```
# Valheim configuration
appid=892970
depotid=892971
#buildid=11422039
#manifestid=9217850553460069452
#version="0.216.9"
buildid=11535571
version="0.217.6"
beta="public-test"
betapassword="yesimadebackups"
```

Then further down by the depotdownloader check (note, I commented out the verify command because I dont know the hash for 2.5.0):
```
    if [ ! -d "depotdownloader-2.5.0" ]; then
      if confirm "Download (~2MB) and unzip DepotDownloader to download Valheim from Steam?"; then
        curl -L https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.5.0/depotdownloader-2.5.0.zip -o depotdownloader-2.5.0.zip
        #verify depotdownloader-2.5.0.zip acee4d813db4e6908b75d348767cf01e
        unzip depotdownloader-2.5.0.zip -d depotdownloader-2.5.0
      fi

      if [ ! -d "depotdownloader-2.5.0" ]; then
        echo "DepotDownloader not found, exiting.."
        exit 1
      fi
    fi
```

@timkurvers - If it was me, I dont know if I would have a separate build for beta. Maybe just have one script which accepts a /beta flag and used the vars in the script, or accepts -beta [depotname] and -betapassword [pw] flags??

**Comment by hvab** [comment]
@osirion Thank you! I don't know why, but with these parameters it still creates the app version 0.216.9...

**Comment by timkurvers** [comment]
Glad you two have working versions! 🥳

Have opened up #31 which has support for the `--beta` flag. I won't be able to get around to merging it today, but later this week hopefully.

**Comment by timkurvers** [comment]
Closing as this is now available on the main branch. Thanks for the detective work! 🙌
